#!/bin/bash
#SBATCH --job-name=boxtaxo_psy
#SBATCH --output=boxtaxo_psy_out.txt
#SBATCH --error=boxtaxo_psy_err.txt
#SBATCH --ntasks=1
#SBATCH --time=400:00
#SBATCH --mem=100Gb
#SBATCH --gres=gpu:1

source ~/.bashrc
module load miniconda/3
module load cuda/11.1
conda activate boxtaxo
cd src
echo ""
echo "TRAIN PSY:"
python main.py --dataset MAG-PSY
echo "ERROR CODE: $?"

